#!/bin/bash

# get a module from puppet-forge
function forge()
{
  AUTHOR=$1
  MODULE=$2
  UPGRADED=$CACHE/{$AUTHOR}_{$MODULE}.lastupgrade
  
  if [ ! -d /etc/puppet/modules/$MODULE ]; then
   echo -e "Installing $AUTHOR/$MODULE"
    sudo puppet module install $AUTHOR/$MODULE
  else
    if [ ! -f $UPGRADED ]; then
      echo -e "Upgrading $AUTHOR/$MODULE"
      sudo puppet module upgrade $AUTHOR/$MODULE
      touch $UPGRADED
    fi
  fi
}

# get a module from github
function gh()
{
  AUTHOR=$1
  REPO=$2
  MOD=$3
  if [ ! -d /etc/puppet/modules/$MOD ]; then
   echo -e "Installing $AUTHOR/$MODULE"
   sudo git clone https://github.com/$AUTHOR/$REPO.git /etc/puppet/modules/$MOD
  else
    echo -e "Pulling changes for $AUTHOR/$MOD"
    cd /etc/puppet/modules/$MOD
    sudo git pull
    cd -
  fi
}

# support for etckeeper
function etckeep()
{
  MSG=$1
  [ -x /usr/bin/etckeeper ] && sudo etckeeper commit "$MSG" 
}

###################################################################################################################
########################################### STARTS HERE ###########################################################
###################################################################################################################
CACHE=/tmp/uboxen
[ ! -d $CACHE ] && mkdir $CACHE

sudo mkdir -p /etc/facter/facts.d

FACTER_UBUSER=$(sudo facter UBUSER)
if [ "$FACTER_UBUSER" = "" ]; then
  FACTER_UBUSER=$(facter id)
  sudo sh -c "echo 'echo UBUSER="$FACTER_UBUSER"' >> /etc/facter/facts.d/profile.sh"
  sudo chmod +x /etc/facter/facts.d/profile.sh
fi

FACTER_HGLOGIN=$(sudo facter HGLOGIN)
FACTER_HGEMAIL=$(sudo facter HGEMAIL)

if [ "$FACTER_HGLOGIN" = "" ] || [ "$FACTER_HGEMAIL" = "" ]; then

   echo -n "Setup Mercurial? (Y/n): "
   read -n 1 hgsetup
   echo
   hgsetup="$(echo $hgsetup | tr '[:upper:]' '[:lower:]')"

   if [ "$hgsetup" = "" ] || [ "$hgsetup" = "y" ]; then

      echo -n "Please enter your Mercurial username: "
      read FACTER_HGLOGIN
      sudo sh -c "echo 'echo HGLOGIN="$FACTER_HGLOGIN"' >> /etc/facter/facts.d/mercurial.sh"

      echo -n "Please enter your Github e-mail: "
      read FACTER_HGEMAIL
      sudo sh -c "echo 'echo HGEMAIL="$FACTER_HGEMAIL"' >> /etc/facter/facts.d/mercurial.sh"
      sudo chmod +x /etc/facter/facts.d/mercurial.sh
   fi
fi

FACTER_GITLOGIN=$(sudo facter GITLOGIN)
FACTER_GITEMAIL=$(sudo facter GITEMAIL)

if [ "$FACTER_GITLOGIN" = "" ] || [ "$FACTER_GITEMAIL" = "" ]; then

   echo -n "Setup Github? (Y/n): "
   read -n 1 gitsetup
   echo
   gitsetup="$(echo $gitsetup | tr '[:upper:]' '[:lower:]')"

   if [ "$gitsetup" = "" ] || [ "$gitsetup" = "y" ]; then

      echo -n "Please enter your Github username: "
      read FACTER_GITLOGIN
      sudo sh -c "echo 'echo GITLOGIN="$FACTER_GITLOGIN"' >> /etc/facter/facts.d/github.sh"

      echo -n "Please enter your Github e-mail: "
      read FACTER_GITEMAIL
      sudo sh -c "echo 'echo GITEMAIL="$FACTER_GITEMAIL"' >> /etc/facter/facts.d/github.sh"
      sudo chmod +x /etc/facter/facts.d/github.sh
   fi
fi

cd /opt/ubuntu-boxen
sudo git pull
cd -

forge puppetlabs stdlib
forge puppetlabs inifile
forge puppetlabs apt 
forge puppetlabs apache
forge puppetlabs vcsrepo 
forge puppetlabs concat 
forge saz sudo
forge saz dnsmasq
forge thomasvandoren etckeeper
forge garethr docker 
forge willdurand composer
forge example42 php
gh Americas puppet-git git

etckeep "Before uBoxen run"
sudo puppet apply /etc/puppet/manifests/uboxen.pp 
etckeep "After uBoxen run"

# Clean module upgrade files
sudo puppet resource tidy $CACHE age=1m 

exit 0