class bash {

   package { [ 'bash', 'bash-completion', 'command-not-found' ] :
      ensure => latest,
   }

   file { '/etc/profile.d/load-puppet-profile.sh':
      content => "# file generated by puppet\n[ -f ~/.bashrc.puppet ] && source ~/.bashrc.puppet\n",
   }
}