class bash {

   package { [ 'bash', 'bash-completion', 'command-not-found' ] :
      ensure => latest,
   }

   $real_file = '/etc/profile.d/load-puppet-profile.sh'

   file { $real_file:
   	ensure  => file,
      content => "# file generated by puppet\n[ -f ~/.bashrc.puppet ] && source ~/.bashrc.puppet\n",
   }

   exec { 'source bash':
   	refreshonly => true,
      command => "source ${real_file}",
   }
}