# if user specified add config to ~/.bashrc.puppet
# else add config to system-wide bashrc.puppet.sh
define bash::rc(
  $content = '', 
  $user = undef,
) {

   include bash
  
   validate_string($content)

   $real_content = $content ? {
      ''      => $name,
      default => "# $name\n$content",
   }

   if $user {
      validate_string($user)
      $real_target = "/home/$user/.bashrc.puppet"

      validate_absolute_path($real_target)
   } else {
      $real_target  = '/etc/profile.d/bashrc.puppet.sh'
      validate_absolute_path($real_target)
   }

   if ! defined(Concat[$real_target]) {
      concat { $real_target : 
         ensure => present,
      }
      concat::fragment { 'systemwide-bashrc-header':
         content => "# file generated by Puppet\n\n",
         target  => $real_target,
         order   => '00',
      }
   }

   concat::fragment { $name:
      target  => $real_target,
      content => "$real_content\n\n",
   }
}